= OGC API - Features Conformance Test Suite

== Scope

This executable test suite (ETS) verifies that an OGC API - Features instance conforms to following and related standards.

* http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] (OGC 17-069r3)
* http://docs.opengeospatial.org/DRAFTS/20-002.html[OGC API - Features - Part 4: Simple Transactions]

Conformance testing is a kind of "black box" testing that examines externally visible characteristics or behaviors of the SUT and is independent of any implementation details.

Several conformance classes are defined in the principal specifications. The ones
listed below are covered by this test suite:

* Core
    - The Core conformance class specifies requirements that all OGC API - Features instances have to fulfill.
    - Originates from http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] (OGC 17-069r3).
* Simple Transactions
    - The Simple Transactions conformance class is optional and just partially implemented.
    - Originates from http://docs.opengeospatial.org/DRAFTS/20-002.html[OGC API - Features - Part 4: Simple Transactions].

== Test requirements

The documents listed below stipulate requirements that must be satisfied by a 
conforming implementation.

1. http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core]

There are some requirements the test suite expects to be satisfied by the service under test:

* The API landing page response must be available in JSON.
* The API definition response must be available in OpenAPI 3.0.
* The conformance classes response must be available in JSON.
* The feature collections metadata and feature collection metadata responses must be available in JSON.
* The feature collections and features must be available in GeoJSON.

== Test suite structure

The test suite definition file (testng.xml) is located in the root package, 
`org.opengis.cite.ogcapifeatures10`. A conformance class corresponds to a &lt;test&gt; element, each
of which includes a set of test classes that contain the actual test methods. 
The general structure of the test suite is shown in Table 1.

.Test suite structure
[cols="2,6a",options=header]
|===
|Conformance class
|Test classes

|Core
|
 * org.opengis.cite.ogcapifeatures10.general.*
 * org.opengis.cite.ogcapifeatures10.apidescription.*
 * org.opengis.cite.ogcapifeatures10.conformance.*
 * org.opengis.cite.ogcapifeatures10.collections.*

|Simple Transactions
|
 * org.opengis.cite.ogcapifeatures10.simpletransactions.*

|===

The Javadoc documentation provides more detailed information about the test 
methods that constitute the suite.

include::how-to-run-the-tests.adoc[]

== Using the REST API

Using the REST API of the TEAM Engine requires some run arguments. These are summarized in Table 2.
The _Obligation_ descriptor can have the following values: M (mandatory), O (optional), or C (conditional).

.Test run arguments
[cols="1,1,1,6",options=header]
|===
|Name
|Value domain
|Obligation
|Description

|iut
|URI
|M
|A URI that refers to the landing page of the service under test. Ampersand ('&amp;') characters must be percent-encoded as '%26'.

|noofcollections
|Integer
|O
|Number of collections under test. -1 means that all collections should be tested. Default: 3

|===
